import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { CollectionStore } from "./collection-store.js";

const GENERATED_DIR = ".vike-content-collection";
const GENERATED_FILE = "types.d.ts";
const HEADER = "// Auto-generated by vike-content-collection — do not edit\n";

export function generateDeclarationFile(
	store: CollectionStore,
	projectRoot: string,
): void {
	const outDir = join(projectRoot, GENERATED_DIR);
	const outFile = join(outDir, GENERATED_FILE);

	mkdirSync(outDir, { recursive: true });

	const content = buildDeclarationContent(store, outDir);

	if (existsSync(outFile)) {
		const existing = readFileSync(outFile, "utf-8");
		if (existing === content) return;
	}

	writeFileSync(outFile, content);
}

const TYPE_HELPERS =
	`type _ResolveSchema<C> = C extends { schema: infer S } ? S : C\n` +
	`type _ResolveContent<M> = M extends { Content: infer C } ? _ResolveSchema<C>\n` +
	`  : M extends { default: { Content: infer C } } ? _ResolveSchema<C>\n` +
	`  : M extends { default: infer D } ? _ResolveSchema<D>\n` +
	`  : never\n` +
	`type _ExtractComputed<C> = C extends { computed: infer Comp }\n` +
	`  ? { [K in keyof Comp]: Comp[K] extends (...args: any[]) => infer R ? R : never }\n` +
	`  : Record<string, never>\n` +
	`type _ResolveComputed<M> = M extends { Content: infer C } ? _ExtractComputed<C>\n` +
	`  : M extends { default: { Content: infer C } } ? _ExtractComputed<C>\n` +
	`  : M extends { default: infer D } ? _ExtractComputed<D>\n` +
	`  : Record<string, never>\n`;

export function buildDeclarationContent(
	store: CollectionStore,
	outDir: string,
): string {
	const collections = store.getAll();

	if (collections.length === 0) {
		return (
			HEADER +
			`declare module 'vike-content-collection' {\n` +
			`  interface CollectionMap {}\n` +
			`}\n\n` +
			`export { };\n`
		);
	}

	const imports: string[] = [];
	const mapEntries: string[] = [];

	for (const collection of collections) {
		const safeName = collection.name.replace(/[^a-zA-Z0-9]/g, "_") || "_root";

		const configRelative = relative(outDir, collection.configPath)
			.replace(/\\/g, "/")
			.replace(/\.(ts|js|mts|mjs)$/, "");

		imports.push(`import type * as _${safeName} from '${configRelative}'`);
		mapEntries.push(
			`    '${collection.name}': {\n` +
				`      metadata: z.infer<_ResolveContent<typeof _${safeName}>>\n` +
				`      computed: _ResolveComputed<typeof _${safeName}>\n` +
				`    }`,
		);
	}

	return (
		HEADER +
		`import type { z } from 'zod'\n` +
		imports.join("\n") +
		"\n\n" +
		TYPE_HELPERS +
		"\n" +
		`declare module 'vike-content-collection' {\n` +
		`  interface CollectionMap {\n` +
		mapEntries.join("\n") +
		"\n" +
		`  }\n` +
		`}\n`
	);
}
