import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { CollectionStore } from "./collection-store.js";

const GENERATED_DIR = ".vike-content-collection";
const GENERATED_FILE = "types.d.ts";
const HEADER = "// Auto-generated by vike-content-collection — do not edit\n";

export function generateDeclarationFile(
	store: CollectionStore,
	projectRoot: string,
): void {
	const outDir = join(projectRoot, GENERATED_DIR);
	const outFile = join(outDir, GENERATED_FILE);

	mkdirSync(outDir, { recursive: true });

	const content = buildDeclarationContent(store, outDir);

	if (existsSync(outFile)) {
		const existing = readFileSync(outFile, "utf-8");
		if (existing === content) return;
	}

	writeFileSync(outFile, content);
}

export function buildDeclarationContent(
	store: CollectionStore,
	outDir: string,
): string {
	const collections = store.getAll();

	if (collections.length === 0) {
		return (
			HEADER +
			`declare module 'vike-content-collection' {\n` +
			`  interface CollectionMap {}\n` +
			`}\n`
		);
	}

	const imports: string[] = [];
	const mapEntries: string[] = [];

	for (const collection of collections) {
		const safeName = collection.name.replace(/[^a-zA-Z0-9]/g, "_") || "_root";

		const configRelative = relative(outDir, collection.configPath)
			.replace(/\\/g, "/")
			.replace(/\.(ts|js|mts|mjs)$/, "");

		imports.push(
			`import type { schema as schema_${safeName} } from '${configRelative}'`,
		);
		mapEntries.push(
			`    '${collection.name}': z.infer<typeof schema_${safeName}>`,
		);
	}

	return (
		HEADER +
		`import type { z } from 'zod'\n` +
		imports.join("\n") +
		"\n\n" +
		`declare module 'vike-content-collection' {\n` +
		`  interface CollectionMap {\n` +
		mapEntries.join("\n") +
		"\n" +
		`  }\n` +
		`}\n`
	);
}
