import { beforeEach, describe, expect, it } from "bun:test";
import {
	type Collection,
	CollectionStore,
} from "../src/plugin/collection-store";
import { buildDeclarationContent } from "../src/plugin/generate-types";

function makeCollection(
	name: string,
	configDir: string,
	configPath: string,
	markdownDir?: string,
): Collection {
	return {
		name,
		type: "content" as const,
		configDir,
		configPath,
		markdownDir: markdownDir ?? configDir,
		entries: [],
	};
}

describe("buildDeclarationContent", () => {
	let store: CollectionStore;
	const outDir = "/project/.vike-content-collection";

	beforeEach(() => {
		store = new CollectionStore();
	});

	it("generates empty CollectionMap when no collections exist", () => {
		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("interface CollectionMap {}");
		expect(content).toContain("Auto-generated by vike-content-collection");
		expect(content).toContain("export { };");
	});

	it("generates a single collection entry", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("import type { z } from 'zod'");
		expect(content).toContain("import type * as _blog from");
		expect(content).toContain("_ResolveContent");
		expect(content).toContain("metadata: z.infer<_ResolveContent<typeof _blog>>");
		expect(content).toContain("computed: _ResolveComputed<typeof _blog>");
		expect(content).not.toContain("export { }");
	});

	it("generates multiple collection entries", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);
		store.set(
			"/project/pages/docs",
			makeCollection(
				"docs",
				"/project/pages/docs",
				"/project/pages/docs/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("metadata: z.infer<_ResolveContent<typeof _blog>>");
		expect(content).toContain("metadata: z.infer<_ResolveContent<typeof _docs>>");
	});

	it("uses relative import paths from the output directory", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("from '../pages/blog/+Content'");
	});

	it("strips file extensions from import paths", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).not.toContain("+Content.ts'");
		expect(content).toContain("+Content'");
	});

	it("sanitizes collection names with special characters for identifiers", () => {
		store.set(
			"/project/pages/docs/guides",
			makeCollection(
				"docs/guides",
				"/project/pages/docs/guides",
				"/project/pages/docs/guides/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("_docs_guides");
		expect(content).toContain(
			"metadata: z.infer<_ResolveContent<typeof _docs_guides>>",
		);
	});

	it("declares module augmentation for vike-content-collection", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("declare module 'vike-content-collection'");
		expect(content).toContain("interface CollectionMap");
	});

	it("includes the do-not-edit header", () => {
		const content = buildDeclarationContent(store, outDir);

		expect(
			content.startsWith("// Auto-generated by vike-content-collection"),
		).toBe(true);
	});

	it("includes _ResolveComputed helper for computed field types", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("_ExtractComputed");
		expect(content).toContain("_ResolveComputed");
		expect(content).toContain("computed: _ResolveComputed<typeof _blog>");
	});

	it("includes _ResolveSchema helper for extended config support", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("_ResolveSchema");
		expect(content).toContain("C extends { schema: infer S }");
	});

	it("handles .mts config extension", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.mts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).not.toContain(".mts");
		expect(content).toContain("+Content'");
	});
});
