import { beforeEach, describe, expect, it } from "bun:test";
import {
	type Collection,
	CollectionStore,
} from "../src/plugin/collection-store";
import { buildDeclarationContent } from "../src/plugin/generate-types";

function makeCollection(
	name: string,
	configDir: string,
	configPath: string,
): Collection {
	return {
		name,
		configDir,
		configPath,
		entries: [],
	};
}

describe("buildDeclarationContent", () => {
	let store: CollectionStore;
	const outDir = "/project/.vike-content-collection";

	beforeEach(() => {
		store = new CollectionStore();
	});

	it("generates empty CollectionMap when no collections exist", () => {
		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("interface CollectionMap {}");
		expect(content).toContain("Auto-generated by vike-content-collection");
	});

	it("generates a single collection entry", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("import type { z } from 'zod'");
		expect(content).toContain("import type { schema as schema_blog }");
		expect(content).toContain("'blog': z.infer<typeof schema_blog>");
	});

	it("generates multiple collection entries", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);
		store.set(
			"/project/pages/docs",
			makeCollection(
				"docs",
				"/project/pages/docs",
				"/project/pages/docs/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("'blog': z.infer<typeof schema_blog>");
		expect(content).toContain("'docs': z.infer<typeof schema_docs>");
	});

	it("uses relative import paths from the output directory", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("from '../pages/blog/+Content'");
	});

	it("strips file extensions from import paths", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).not.toContain("+Content.ts'");
		expect(content).toContain("+Content'");
	});

	it("sanitizes collection names with special characters for identifiers", () => {
		store.set(
			"/project/pages/docs/guides",
			makeCollection(
				"docs/guides",
				"/project/pages/docs/guides",
				"/project/pages/docs/guides/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("schema_docs_guides");
		expect(content).toContain(
			"'docs/guides': z.infer<typeof schema_docs_guides>",
		);
	});

	it("declares module augmentation for vike-content-collection", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.ts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).toContain("declare module 'vike-content-collection'");
		expect(content).toContain("interface CollectionMap");
	});

	it("includes the do-not-edit header", () => {
		const content = buildDeclarationContent(store, outDir);

		expect(
			content.startsWith("// Auto-generated by vike-content-collection"),
		).toBe(true);
	});

	it("handles .mts config extension", () => {
		store.set(
			"/project/pages/blog",
			makeCollection(
				"blog",
				"/project/pages/blog",
				"/project/pages/blog/+Content.mts",
			),
		);

		const content = buildDeclarationContent(store, outDir);

		expect(content).not.toContain(".mts");
		expect(content).toContain("+Content'");
	});
});
